name: Get & Cache Dependencies
description: demo of custom actions
inputs:
  use-cache:
    description: Flag to use cached dependencies
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.use-cache != 'true'
      run: npm ci
      shell: bash